### ISSUE TITLE
Some module is looping 100K times when you import it

### ISSUE THREAD

**Issue by AbeHandler** [fortytw0/needfinder#13]
If you run `py -m src.bm25` there is some counter that loops 100K times. There seems to be something that should be hidden behind a `if __name__ == '__main__'` but is not

<img width="1440" alt="Screen Shot 2022-06-29 at 6 54 26 PM" src="https://user-images.githubusercontent.com/1252925/176570243-1c331e30-424b-4d47-a37a-af1b14517c92.png">

**Comment by fortytw0** [comment]
This is the module that loops over the corpus, it reads a maximum of 1e5 lines. This is working as intended!
