### ISSUE TITLE
Clustering methods?

### ISSUE THREAD

**Issue by AbeHandler** [fortytw0/needfinder#2]
Just making a note here that we might want to implement clustering methods. We could try: 
- agglomerative clustering over the text similarity vectors
- topic modeling 

None of these are urgent, and it is not clear we should definitely do this, but am making an issue so we don't forget.

**Comment by fortytw0** [comment]
I feel this can be closed? We are doing clustering, but on cosine-similarity

**Comment by AbeHandler** [comment]
Yes. Lets close it.
